### ISSUE TITLE
As IRMA system, when the file is not available on disk and the user submit it again, I should download it

### ISSUE THREAD

**Issue by guillaumededrie** [quarkslab/irma-frontend#106]
See the problem and the recommendation from @fmonjalet there: https://github.com/quarkslab/irma-frontend/issues/105.

**Comment by ch0k0bn** [comment]
done since 1.2.1 https://github.com/quarkslab/irma-frontend/commit/dd836ed2652d45bdec6c798279aa2d0f8c1d7efe
