### ISSUE TITLE
Search feature not always returning the last scan

### ISSUE THREAD

**Issue by deloittem** [quarkslab/irma-frontend#123]
Hello,

I think there is a problem related to the search feature.

When a file has been scanned multiple times, sometime the search feature doesn't return the link to the last scan but to an older one. It is not always the case and happens randomly.

It seems related to the sqlobject query: 
    ```.distinct(FileWeb.name)```

**Comment by ch0k0bn** [comment]
Some steps are missing in UI. Searching files aims at finding name or hash present in base, once retrieved through files-list , we should output a list of available scans (and results) through files-get.
View for files-get is missing atm.

**Comment by deloittem** [comment]
Would it not be a good idea to just return the last scan for the moment ... waiting for the new feature ?

**Comment by ch0k0bn** [comment]
fixed by 5f1d1e49c7acf4eef61dd3675e032d80962eaec8
