### ISSUE TITLE
Bower install issues

### ISSUE THREAD

**Issue by jhemp** [quarkslab/irma-frontend#13]
I see the follwoing after the bower installation

bower angular-strap#~2.0.2             validate 2.0.5 against https://github.com/mgcrea/angular-strap.git#~2.0.2
bower                                 ENOTFOUND Package option not found

which seems that the re is something not available anymore or similar.

After this I cannot continue the installation

**Comment by thoersch** [comment]
What was the issue??

**Comment by guillaumededrie** [comment]
Hi @thoersch,
This issue is 6 months old. Do you think you've got the same problem?

If you're not sure, you can open a new issue and we will reference the new one with this one.

Regards,
Guillaume
