### ISSUE TITLE
[Feature-request] IRMA python + on_complete/blocking wait

### ISSUE THREAD

**Issue by commial** [quarkslab/irma-frontend#75]
Hi!

I would like to use the IRMA frontend API from a Python script.
So I got two points (if you consider their are not related, I can open a second issue).

Firstly, regarding a potential `irma-python` module, should I use the `irma-frontend/frontend/cli/apiclient.py`?
It would be great to have an external standalone module, with just a few dependency (like `python-requests`).
That way, one can launch a scan with (fictive sample API):
```Python
from irma import IrmaServer, IrmaScan
isrv = IrmaServer.from_url("http://irma.example.com")
scan = IrmaScan(isrv)
scan.add_files("bad.exe")
scan.launch()
...
print "Probes", isrv.probes
...
for scan in isrv.scans:
    print scan.results
```

Secondly, giving this kind of API, it would be great to have both blocking and non-blocking calls to wait for a scan to end.
That is to say, a first API (for instance, `scan.wait()`) which gives back control to caller when the scan is complete. And a second one (for instance, `scan.on_complete(callback)`), which can use the first one in a `Thread`, which is asynchronous and call an input *callback* when the scan is complete.

Please ask if you need to have more details/I'm not clear enough.

**Comment by ch0k0bn** [comment]
For your first question, yes you should use IrmaApiClient and yes it would be better to have a standalone client. We will do this in a near future (low priority)
I also agree that your suggestion of a "synchronous" API could help sometimes but it is not planned.

**Comment by ch0k0bn** [comment]
python command line tool is now available at https://github.com/quarkslab/irma-cli
