### ISSUE TITLE
Indicate anvirus signature DB version or date in scan results

### ISSUE THREAD

**Issue by Lastpixl** [quarkslab/irma-frontend#80]
Hello

This is a feature request.
Antivirus scan results already indicate the antivirus version. It would be nice to also indicate the signature database version or date.

Thanks for considering this issue.
Best regards

**Comment by ch0k0bn** [comment]
Hello,

We have a full list of AV database file hash and date, but not displayed yet. You could try it by querying a specific scan result and add "formatted=no" as GET parameter.
Example: http://127.0.0.1/api/v1/scans/<scanid>/results/1?formatted=no

Still looking how to properly display that info.

**Comment by ch0k0bn** [comment]
since in IRMA v2.0 a virus db version is displayed when available (wip)
