### ISSUE TITLE
Upload files with utf-8 encoded name

### ISSUE THREAD

**Issue by fmonjalet** [quarkslab/irma-frontend#83]
Hi,

It would be nice to be able to upload files with a name encoded in utf-8 rather than ascii (for example containing accents). One possible way to do that would be to `escape(urldecode(upfile.raw_filename))` (at [scans.py:146](https://github.com/quarkslab/irma-frontend/blob/master/frontend/api/controllers/scans.py#L146)) rather than using the bottle escaping as is (which is what `upfile.filename` is, according to the [Bottle doc](http://bottlepy.org/docs/dev/api.html#bottle.FileUpload).

I think it would be very valuable to users to be able to keep the file name they uploaded (and globally). What do you think?

**Comment by ch0k0bn** [comment]
solved by commit 01361543ebab6ff237e261d26e0cf00cca3279ca
