### ISSUE TITLE
Handle big files

### ISSUE THREAD

**Issue by fmonjalet** [quarkslab/irma-frontend#84]
Hi,

I noticed in at least two places that files are entirely read in RAM before being written to disk. This could cause issues if big files have to be scanned (an ISO for example, or a big document archive).

Two examples:
- [scans.py:147](https://github.com/quarkslab/irma-frontend/blob/master/frontend/api/controllers/scans.py#L147): there should be a way to use the file object rather than reading the whole file.
- [irma-common/irma.ftp.handler:178](https://github.com/quarkslab/irma-common/blob/master/irma/ftp/handler.py#L178): the lambda function should could update a hash and write the data to the disk rather than storing the file chunks in RAM. This would allow never to have the whole file in RAM (the current implementation copies it at least two times in RAM).

Do you think it would be possible to fix these issues? (There must be other places where this is the case, these are just two examples I found.)

Cheers,

Florent

**Comment by ch0k0bn** [comment]
Files are currently limited to 100Mb (set as nginx post data limit). Trying to work on chunks would be better though.

**Comment by ch0k0bn** [comment]
fixed by 5f1d1e49c7acf4eef61dd3675e032d80962eaec8
